### ISSUE TITLE
Runtime error (TypeErrorException): sequence item 1: expected bytes or byte array, str found

### ISSUE THREAD

**Issue by marialarsson** [Digital-Structures/ghpythonremote#16]
The component goes red when I run it. I get the following error message:

```
Connecting...
DEBUG: ghpythonremote.connectors:
Connecting. Timeout in 10 seconds.
Runtime error (TypeErrorException): sequence item 1: expected bytes or byte array, str found
```

Thanks for developing this tool, I have been looking for something like this for a long time!

**Comment by pilcru** [comment]
This error is normally fixed by installing a newer version of IronPython. There is a guide available [here](https://wiki.mcneel.com/grasshopper/cpython).
