### ISSUE TITLE
Missing file IronPython_to_CPython.py on install

### ISSUE THREAD

**Issue by millen1m** [Digital-Structures/ghpythonremote#26]
I think 'IronPython_to_CPython.py' is missing in setup.py in 'package_data'.

**Comment by pilcru** [comment]
Thanks for reporting this! I hadn't really planned on distributing this file with the package, its only use being to test an IronPython to CPython connection without launching Rhino. Did you have a different use case, or do you see an error message about it somewhere?

Of course, I could also label it as a test file more clearly, if that helps.

**Comment by millen1m** [comment]
Actually, the install of the package did work, but the instructions on this page: https://www.food4rhino.com/app/gh-python-remote say to then run `ghpythonremote._configure_ironpython_installation`, and in that step it tries to read the IronPython_to_CPython.py file but it cannot find it and fails.

**Comment by pilcru** [comment]
Fixed in 8d46e840da2a7d64ef0d9253d690b90a955a8758
