### ISSUE TITLE
example files missing after pip install

### ISSUE THREAD

**Issue by yijiangh** [Digital-Structures/ghpythonremote#28]
After following the instructions:
```
pip install gh-python-remote --upgrade --no-binary=:all:
python -m ghpythonremote._configure_ironpython_installation
```

My conda console tells me:

```
Successfully installed gh-python-remote-1.2.1 plumbum-1.6.7 rpyc-4.1.1
...
IOError: [Errno 2] No such file or directory: 'C:\\Users\\harry\\.conda\\envs\\py27\\lib\\site-packages\\ghpythonremote\\examples\\CPython_to_GH.py'
```

And these are the files in my `examples` folder:
![image](https://user-images.githubusercontent.com/11905844/62329292-c80ebc80-b4b5-11e9-91d0-05f06b543a30.png)

It's strange that this happens since we already have these example files marked as `package_data` in the `setup.py` ([here](https://github.com/Digital-Structures/ghpythonremote/blob/036d6977116b6097d5dc652a1101c439cdcda0b7/setup.py#L62)). Do we need to add them in the `MANIFEST.in` as well?

**Comment by pilcru** [comment]
This will go in the next patch release with other bugfixes. It should be easily manually fixed in the meantime, given the rest of the installation works and it's just that one file that doesn't get copied.
