### ISSUE TITLE
importing methods from "ortools" library

### ISSUE THREAD

**Issue by op-rt** [Digital-Structures/ghpythonremote#32]
Hi,

I'm facing an issue when trying to load a specific method from the Google "Or-Tools" library.

I have installed the library in the correct environment ("rhinoremote") and loading it from there works fine:
![Annotation 2020-01-11 163020](https://user-images.githubusercontent.com/28729303/72206560-bb908600-348f-11ea-8d8f-5aac58a6a757.png)

I can import `ortools.sat.python` via the sticky dictionary but can't seem to figure out how to access the `cp_model` method from there:

![Annotation 2020-01-11 164425](https://user-images.githubusercontent.com/28729303/72206723-a9174c00-3491-11ea-92a6-4fa2950758bc.png)

For clarity, the tree structure:
```
ortools__
         sat__
              python__
                       __init__.py
                       cp_model.py
                       cp_model_helper.py
                       vizualisation.py
```
              

Am i missing something obvious or is it a limitation from GhPythonRemote ?

**Comment by pilcru** [comment]
Can you try with importing `ortools.sat.python.cp_model` in the GHPythonRemote modules input? I've never been able to reliably configure submodule import through the interface. You might even have to have both imports, in order:
```
ortools.sat.python
ortools.sat.python.cp_model
```

**Comment by op-rt** [comment]
Thank you for the reply. I had already tried this as well but without luck.
This is the error I get (even with both imports):

![Annotation 2020-01-13 210056](https://user-images.githubusercontent.com/28729303/72287705-cee65180-3647-11ea-956e-4b3d719404a2.png)

and in the terminal:

```
2020-01-13 22:27:38,301 - ghpythonremote.pythonservice - DEBUG -
Exception caught
Traceback (most recent call last):
  File "C:\Users\solub\Anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 323, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\solub\Anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 580, in _handle_call
    return obj(*args, **dict(kwargs))
  File "C:\Users\solub\Anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\service.py", line 160, in getmodule
    return __import__(name, None, None, "*")
  File "C:\Users\solub\Anaconda3\envs\rhinoremote\lib\site-packages\ortools\sat\python\cp_model.py", line 59, in <module>
    from ortools.sat import pywrapsat
  File "C:\Users\solub\Anaconda3\envs\rhinoremote\lib\site-packages\ortools\sat\pywrapsat.py", line 103
    def OnSolutionCallback(self) -> "void":
                                 ^
SyntaxError: invalid syntax
```

**Comment by pilcru** [comment]
So this seems to be working here, I can import `ortools.sat.python.cp_models` as an input in "modules", and then access that through the sticky dictionnary.

However, I don't have the type hinting (`-> "void"`) on line 103 of pywrapsat.py where you get a syntax error. I don't think python 2 support these, so it looks like the python 3 version of the files got installed instead of python 2, on your setup. Maybe try reinstalling ortools?

**Comment by op-rt** [comment]
Thank you for the testing on your side ! This thing is a mystery to me, I have uninstalled and re-installed ortools in the `rhinoremote` environement and still get the same error.

_installation in anaconda prompt_
```

(rhinoremote) C:\Users\solub>pip install ortools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting ortools
  Using cached https://files.pythonhosted.org/packages/fb/f3/dec199235f613a3c7b2724c08b26a92e21061074382d9f686e541b47d7d2/ortools-7.3.7083-cp27-cp27m-win_amd64.whl
Collecting six>=1.10 (from ortools)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting protobuf>=3.9.0 (from ortools)
  Using cached https://files.pythonhosted.org/packages/02/ba/2d33a1ea34f672c088c08f0f8e70292ff770c7f0c2481690cae378d33d66/protobuf-3.11.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\solub\anaconda3\envs\rhinoremote\lib\site-packages (from protobuf>=3.9.0->ortools) (41.0.1)
Installing collected packages: six, protobuf, ortools
Successfully installed ortools-7.3.7083 protobuf-3.11.2 six-1.13.0
```

_Error when importing in "modules"_

<img width="926" alt="Annotation 2020-01-14 013147" src="https://user-images.githubusercontent.com/28729303/72303502-cacd2a80-366d-11ea-81cc-18afb813b0f9.png">

**Comment by pilcru** [comment]
Sorry, I started a typo that you reproduced. `ortools.sat.python.cp_model`, no "s" at model.

**Comment by op-rt** [comment]
It's me, I should have been more careful. It does work now !
Thank you for pointing me so quickly in the right direction.

Wishing you the best for this new year.
