### ISSUE TITLE
Installation issue - Runtime error (ArgumentTypeException): expected buffer, got bytes

### ISSUE THREAD

**Issue by ric3U** [Digital-Structures/ghpythonremote#34]
Hi,
Thank you for your reply on Food4Rhino. 
I am trying to use python remote on Rhino 5 SR13 and GH 0.9.0076. Python 2.7 Anaconda2.
I followed the step of the installation but when I open the example file GH_python_remote and change the paths I get this error message:

DEBUG: ghpythonremote.helpers:
 Directly trying python executable at C:\Users\Hp\Anaconda2\envs\rhinoremote

DEBUG: ghpythonremote.connectors:
Using python executable: C:\Users\Hp\Anaconda2\envs\rhinoremote\python.exe
DEBUG: ghpythonremote.connectors:
Using rpyc_server module: C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\pythonservice.py
DEBUG: ghpythonremote.connectors:
Using port: 50011
DEBUG: ghpythonremote.connectors:
Using log_level: DEBUG
DEBUG: ghpythonremote.connectors:
Using working_dir: C:\Users\Hp\Downloads\ghpythonremote-1.3.1\ghpythonremote-1.3.1\ghpythonremote\examples
INFO: ghpythonremote.connectors:
Connecting...
DEBUG: ghpythonremote.connectors:
Connecting. Timeout in 10 seconds.
Runtime error (ArgumentTypeException): expected buffer, got bytes
Traceback:
  line 469, in sync_request, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 105, in _connect, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\service.py"
  line 44, in connect_channel, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 99, in connect, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 141, in _get_connection, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
  line 54, in script
  line 267, in write, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\stream.py"
  line 74, in send, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\channel.py"
  line 259, in _send, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 475, in _async_request, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 493, in async_request, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 502, in root, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 213, in on_connect, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\service.py"
  line 56, in connect_stream, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 53, in __init__, "C:\Users\Hp\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"

Thank you in advance for your help

**Comment by pilcru** [comment]
Thanks for your report, I've got a fix for this that will be added to the next version I release. Next release will probably be early May.

If you want to fix it now on your computer, you can either:
- Upgrade your IronPython version in Rhino, see https://compas-dev.github.io/main/gettingstarted/cad/rhino5_windows.html
- Fix the file in `%APPDATA%\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\monkey.py` with the [latest version](https://raw.githubusercontent.com/Digital-Structures/ghpythonremote/0ab1e8894b065f3c58740415779279527520e81f/ghpythonremote/monkey.py)
