### ISSUE TITLE
ghPythonRemote for Python v3+ ?

### ISSUE THREAD

**Issue by mroberts77** [Digital-Structures/ghpythonremote#37]
Any chance an update for python3 could be available to tap into external data and use the powerful processing capacity of python, like pandas, numpy, etc and some arduino stuff?

**Comment by pilcru** [comment]
This package cannot work with the language Python 3 as long as Rhino uses IronPython 2. Python 2 is still working well, including numpy, scipy, pandas and all the Arduino stuff I've come across.

This has been documented in issue #1 and others.
