### ISSUE TITLE
Missing example files

### ISSUE THREAD

**Issue by dc366** [Digital-Structures/ghpythonremote#40]
The example python_to_GH.py expects a GH user component TestClusterGHPR. However,  ghpythonremote._configure_ironpython_installation does not copy this file to the User Objects folder. There are also other example files which are not copied anywhere.

**Comment by pilcru** [comment]
Fixed and tested in v1.4.4 for the TestClusterGHPR file. For the other "example" files, there are really just test files that I use and do not make an example of anything different than what is already included in the normal installation, so I think they do not need to go into the user installation.

Thanks for the report!

**Comment by dc366** [comment]
Thanks! I actually found the IronPython_to_CPython file helpful as it allows me to access external packages AND escape the Grasshopper canvas while allowing the Rhino instance to be interactive once a script finishes.

**Comment by pilcru** [comment]
So you are using that file in the Rhino Python editor, without getting GH involved? That's not a usecase I've heard about before. How do you deal with keeping the connection open, do you have 2 scripts side-by-side? Or do you reopen a new CPython each time you run your script?

I'd be willing to add a dedicated example + documentation for that if it's useful to others.

**Comment by dc366** [comment]
Yes, I am running it from the Rhino Python editor. I just started playing with this, but my thinking is that I can run the script to start the `rpy` connection and sticky `rpy` and the modules I am interested in (I had to fix the reference from `sticky` to `sc.sticky` (`import scriptcontext as sc`). You may need to open Grasshopper once so that it loads all the plugins, so that `import ghpythonremote` is a valid reference.

When the script completes, the connection remains open, and I can access CPython using `sc.sticky['rpy']` in other scripts. Then I can start playing with `rpy` within other Rhino python scripts without having to restart Rhino and re-establish the connection each time I make a change.
