### ISSUE TITLE
Install gh-python-remote

### ISSUE THREAD

**Issue by SPI-MAG** [Digital-Structures/ghpythonremote#41]
Hi,

I run into this issue while trying to install gh-python-remote.
```
C:\Users\mag>pip install gh-python-remote --upgrade
ERROR: Could not find a version that satisfies the requirement gh-python-remote (from versions: none)
ERROR: No matching distribution found for gh-python-remote
```
What am I missing?

Thanks for your help!

Best,
Gian

**Comment by pilcru** [comment]
Hi, 

What is the python and pip version you are running this on? It looks like you have no virtual environment activated, so there's a good chance you are running on python 3, which is not compatible with gh python remote.

**Comment by SPI-MAG** [comment]
> Hi,
> 
> What is the python and pip version you are running this on? It looks like you have no virtual environment activated, so there's a good chance you are running on python 3, which is not compatible with gh python remote.

Hi Pierre,

thanks for your quick reply. Yes, that is correct. I repeated the procedure of creating a rhinoremote environnement using python 2.7 and it worked. However, when I run the example GH_python_remote is get another issue.

```
`WARNING: ghpythonremote.helpers:
conda not found in your Windows %PATH%, cannot fetch environment by name.
Falling back to getting python path from Windows %PATH%.

DEBUG: ghpythonremote.connectors:
Using python executable: C:\Users\mag\AppData\Local\Microsoft\WindowsApps\python.exe
DEBUG: ghpythonremote.connectors:
Using rpyc_server module: C:\Users\mag\AppData\Roaming\McNeel\Rhinoceros\7.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\pythonservice.py
DEBUG: ghpythonremote.connectors:
Using port: 53775
DEBUG: ghpythonremote.connectors:
Using log_level: DEBUG
DEBUG: ghpythonremote.connectors:
Using working_dir: C:\Users\mag\AppData\Roaming\Grasshopper\UserObjects\gh-python-remote\examples
INFO: ghpythonremote.connectors:
Connecting...
DEBUG: ghpythonremote.connectors:
Connecting. Timeout in 10 seconds.
Runtime error (RuntimeException): Remote python C:\Users\mag\AppData\Local\Microsoft\WindowsApps\python.exe failed on launch. Does the remote python have rpyc installed?

Traceback:
  line 163, in _get_connection, "C:\Users\mag\AppData\Roaming\McNeel\Rhinoceros\7.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
  line 52, in __init__, "C:\Users\mag\AppData\Roaming\McNeel\Rhinoceros\7.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
  line 54, in script
```


How do I specify to use python 2.7 ?
C:\Users\mag\AppData\Local\Microsoft\WindowsApps\python.exe
Here it runs python 3.9

Thank you!

**Comment by pilcru** [comment]
Most likely when you installed conda, you did not select the option to have the `conda` command be added to your path. You can pass the path to the python interpreter you want to the GH Python Remote component. That would be replacing `conda://rhinoremote` with something like `C:/Users/mag/Anaconda3/envs/rhinoremote/python.exe` (if you are using Anaconda) in the example files.

Run `conda env list` in the conda command to get the list of your current envs and their location. Other env managers usually have similar commands.

You can also edit your Windows path to have it include the conda command: https://stackoverflow.com/questions/44597662/conda-command-is-not-recognized-on-windows-10
