### ISSUE TITLE
Grasshopper crashes when adding time and datetime libraries

### ISSUE THREAD

**Issue by elnazta** [Digital-Structures/ghpythonremote#43]
Hi, I can successfully add time and datetime to the modules, but once I try to type import the following script into my GHPython Script:
`import scriptcontext
time= scriptcontext.sticky['time']
datetime= scriptcontext.sticky['datetime']
`
The whole Rhino and Grasshopper crashes. Any idea why this would be happening? I also noticed that this happens when I try to import csv besides time and datetime. Meaning this doesn't happen when a GHPython Script only has time and datetime.

**Comment by pilcru** [comment]
Hi, this seems to be working here, I have also tested using basic functions from these packages. Do you have something else running in your script? Are you successfully connected to the remote Python environment? Have the packages you want to use been referenced for use before starting the connection?

Please share a minimal failing gh file if you cannot get this to work.

Are you sure you need to access these packages through GH Python Remote? As far as I remember, they work fine in IronPython and thus vanilla Rhino/GH.
