### ISSUE TITLE
some modules work failed -"Runtime error (SyntaxErrorException): invalid syntax"

### ISSUE THREAD

**Issue by liariel** [Digital-Structures/ghpythonremote#47]
The modules about numpy, scipy, matplotlib can work successfully in ghpython.
There will be "Runtime error (SyntaxErrorException): invalid syntax" when the module about lhsmdu imported.
The module about lhsmdu can work in vscode rhinoremote.

**Comment by pilcru** [comment]
Where is this error happening exactly? What is the code you are trying to run?

This module seems to work fine here. Here are some general troubleshooting steps for using a new package with GHPythonRemote, make sure that:
- `lhsmdu` is installed in your remote Python environment (in a windows command line, activate the env, then `pip install lhsmdu`);
- `lhsmdu` is imported in the GHPythonRemote connection in your Grasshopper canvas (`lhsmdu` is on a new line in the "modules" input of the GHPytonRemote component, in the GH file where you want to use it);
- you have restarted the GHPythonRemote connection after modifying the "modules" input (turn the "run" input of the GHPythonRemote component to `False` then `True` again);
- `lhsmdu` is defined in the Python script component where you are trying to use it (this line is needed in your Python script in GH: `lhsmdu = scriptcontext.sticky['lhsmdu']`)

With these steps done, I can run this basic example of this module with no error:
```python
import scriptcontext
np = scriptcontext.sticky['numpy']
lhsmdu = scriptcontext.sticky['lhsmdu']

l = lhsmdu.createRandomStandardUniformMatrix(2, 20)  # Monte Carlo sampling
k = lhsmdu.sample(2, 20)  # Latin Hypercube Sampling with multi-dimensional uniformity
k = np.array(k)
l = np.array(l)
print(k)
print(l)
```
