### ISSUE TITLE
Remote console remains empty on Windows 7

### ISSUE THREAD

**Issue by pilcru** [Digital-Structures/ghpythonremote#8]
(From food4rhino)

Running ghpythonremote in windows 7, GH to Python, the console window that opens remains empty. The remote traceback is lost on errors, it is not redirected to GH.

**Comment by tarabishy2020** [comment]
@pilcru I am facing the same issue.
The console is empty, and I am getting this error

"""
INFO: ghpythonremote.connectors:
Connecting...
DEBUG: ghpythonremote.connectors:
Connecting. Timeout in 10 seconds.
Runtime error (TypeErrorException): sequence item 1: expected bytes or byte array, str found
Traceback:
  line 492, in async_request, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 70, in connect, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\classic.py"
  line 117, in _get_connection, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
  line 49, in script
  line 471, in sync_request, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 501, in root, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 195, in on_connect, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\service.py"
  line 100, in _connect, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\service.py"
  line 44, in connect_channel, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 55, in connect_stream, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 94, in connect, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 36, in __init__, "C:\Users\----\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
"""

**Comment by tarabishy2020** [comment]
Fixed the error by installing IronPython 2.7.5, but the window is still empty.

**Comment by pilcru** [comment]
These are two separate issues, the `Runtime error (TypeErrorException): sequence item 1: expected bytes or byte array, str found` has solutions on the [food4rhino](https://www.food4rhino.com/app/gh-python-remote?page=1) forum, and now in #16.

**Comment by pilcru** [comment]
Closing as Rhino 7 does not provide support on Windows 7.
