### ISSUE TITLE
Make ghpythonremote compatible with Rhino 6

### ISSUE THREAD

**Issue by pilcru** [Digital-Structures/ghpythonremote#9]
This should be just a matter of changing paths, although the question remains to install for both versions if possible or only one, when running `python -m ghpythonremote._configure_ironpython_installation`.

**Comment by loudonicus** [comment]
Have you had more thoughts on this? Could you give a step for a hint of where to look for the necessary paths to change?

**Comment by pilcru** [comment]
Sorry this is all taking so long, but for what it's worth replacing the `python -m ghpythonremote._configure_ironpython_installation` command with this one should work for Rhino 6:

`python -m ghpythonremote._configure_ironpython_installation "%APPDATA%\McNeel\Rhinoceros\6.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib"`

Make sure you have dropped the GhPython component at least once on the canvas of Grasshopper in Rhino 6, before running that command.
